trigger:
- main
 
pool:
  vmImage: windows-latest’
 
variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
 
steps:
- task:  NodeTool@0
  displayName: ‘Install node v12’
  inputs:
     versionSpec: ‘12.19.0’
 
- task: Npm@1
  displayName: ‘Install node packages’
  inputs:
     commands: ‘install’
     workingDir: ‘$(System.DefaultWorkingDirectory)’
 
- task: PowerShell@2
  displayName: ‘Run tests’
  inputs:
     targetType: ‘inline’
     script: |
        echo ‘Running tests…’
        npm run test
 
- task: PowerShell@2
  displayName: ‘Build project’
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  inputs:
     targetType: ‘inline’
     script: |
        echo ‘Building project…’
        npm run build